#!/bin/bash
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
echo "source r.diag_autocomplete.dot"  > ${profilePath}
#echo "#${packageName%%_*}_HOME=${packageHome}" >> ${profilePath}
#echo "export DIAGNOSTIQUE=\${DIAGNOSTIQUE:-${packageHome}}" >> ${profilePath}
